M48
; DRILL file {KiCad (6.0.7)} date Wed Jan 18 18:15:29 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T18:15:29-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.7465Y2.287
X2.0142Y2.287
T2
X1.1972Y1.1719
X1.9599Y1.132
X1.9606Y0.5993
T0
M30
