M48
; DRILL file {KiCad 7.0.8} date Sun Jul 13 17:11:34 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-13T17:11:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X1.7465Y2.287
X2.0142Y2.287
T2
X1.1972Y1.1719
X1.9599Y1.132
X1.9606Y0.5993
T0
M30
