#ifndef CONFIG_H
#define CONFIG_H

#define ST(A) #A
#define STR(A) ST(A)

#define DEFAULT_USERNAME "admin"

#define DEVICE_NAME_PREFIX "SHIFTR"

#define WEB_SERVER_PORT 80

#define DIRCON_TCP_PORT 8080
#define DIRCON_MAX_CLIENTS 3
#define DIRCON_NOTIFICATION_INTERVAL 1000

#define BLE_SCAN_INTERVAL 1000
#define BLE_CONNECT_INTERVAL 1000
#define BLE_CONNECT_TIMEOUT 10

#endif
