// ##########################################################################
// ### This file is generated by build and Continuous Integration scripts ###
// ###   .github/workflows/build.py for local development environment     ###
// ###   .github/workflows/build.yml for CI environment                   ###
// ### Changes will be overwritten on the next build!                     ###
// ##########################################################################

#ifndef VERSION_H
#define VERSION_H
#define VERSION "v1.3.1"
#define VERSION_MAJOR 1
#define VERSION_MINOR 3
#define VERSION_PATCH 1
#define VERSION_BUILD "3111a76"
#define VERSION_TIMESTAMP "2025-Feb-17 17:08:18"
#endif
