/*
 * Copyright (C) 2020  Anthony Doud & Joel Baranick
 * All rights reserved
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#pragma once

#include <Arduino.h>

String OTAStyle =
    "<style>"
    "body{background-color:#f0f0f0;font-family:Arial, sans-serif;font-size:14px;color:#333;}"
    "#file-input,input{width:90%;height:44px;border-radius:4px;margin:10px 5%;font-size:15px;}"
    "input{background:#ffffff;border:1px solid #ddd;padding:0 15px;}"
    "#file-input{line-height:44px;text-align:left;display:block;cursor:pointer;color:#333;}"
    "#bar,#prgbar{background-color:#e0e0e0;border-radius:10px;}"
    "#bar{background-color:#4CAF50;width:0%;height:20px;}"
    "form{background:#ffffff;max-width:300px;margin:50px auto;padding:20px;border-radius:8px;text-align:center;box-shadow: 0 4px 8px rgba(0,0,0,0.1);}"
    ".btn{background:#007BFF;color:#ffffff;cursor:pointer;border:none;padding:10px 15px;border-radius:5px;}"
    ".btn:hover{background:#0056b3;}"
    "</style>";

/* Login page */
String OTALoginIndex =
    "<form name='loginForm'>"
    "<h1>Firmware Update Login</h1>"
    "<input name='userid' placeholder='User ID'> "
    "<input name='pwd' placeholder='Password'> "
    "<input type='submit' onclick='check(this.form)' class='btn' value='Login'>"
    "</form>"
    "<script>"
    "function check(form) {"
    "if(form.userid.value=='admin' && form.pwd.value=='admin'){"
    "window.open('/OTAIndex');"
    "}else{"
    "alert('Error: Incorrect Username or Password');"
    "}"
    "}"
    "</script>" +
    OTAStyle;

String noIndexHTML =
    "<!DOCTYPE html>"
    "<html>"
    "<body>"
    "<h2>The webserver files need to be updated.</h2>"
    "Please enter the credentials for your network or upload a new filesystem image using the link below."
    "<form action='/send_settings'>"
    "<p><label for='ssid'>SSID:</label></p>"
    "<input type='text' id='ssid' name='ssid' value='' />"
    "<p><label for='password'>Password:</label></p>"
    "<input type='password' id='password' name='password' value='' />"
    "<input type='submit' value='Submit' class='btn'/>"
    "</form>"
    "<form action='/reboot.html'>"
    "<input type='submit' value='Reboot!' class='btn'/>"
    "</form>"
    "<p style='text-align: center;'><strong><a href='login'>Update Firmware</a></strong></p>"
    "</body>"
    "</html> " +
    OTAStyle;

/* Server Index Page */
String OTAServerIndex =
    "<body>"
    "<div style='width:400px;padding:20px;border-radius:10px;border:solid 2px #e0e0e0;margin:auto;margin-top:20px;background-color:#fff;'>"
    "<div style='text-align:center;font-size:18px;font-weight:bold;margin-bottom:12px;'>SmartSpin2k OTA</div>"
    
    "<div id='github-release-section' style='margin-bottom:20px;border-bottom:1px solid #e0e0e0;padding-bottom:20px;display:none;'>"
    "<div style='text-align:center;font-size:14px;font-weight:bold;margin-bottom:10px;'>GitHub Release</div>"
    "<div id='release-info' style='font-size:12px;padding:10px;background-color:#f5f5f5;border-radius:4px;'></div>"
    "<button id='install-btn' onclick='downloadAndInstall()' class='btn' style='width:100%;margin-top:10px;display:none;background-color:#28a745;'>Download & Install Update</button>"
    "<div id='download-progress' style='background-color:#e0e0e0;border-radius:8px;margin-top:10px;display:none;'>"
    "<div id='dl-prg' style='width:0%;background-color:#007bff;padding:2px;border-radius:8px;color:white;text-align:center;'>0%</div>"
    "</div>"
    "</div>"
    
    "<div style='text-align:center;font-size:14px;font-weight:bold;margin-bottom:10px;'>Manual Upload</div>"
    "<form method='POST' action='#' enctype='multipart/form-data' id='upload-form'>"
    "<input type='file' name='update' style='margin-bottom:10px;'>"
    "<input type='submit' value='Update' class='btn' style='width:100%;'>"
    "</form>"
    "<div style='background-color:#e0e0e0;border-radius:8px;margin-top:10px;'>"
    "<div id='prg' style='width:0%;background-color:#4CAF50;padding:2px;border-radius:8px;color:white;text-align:center;'>0%</div>"
    "</div>"
    "<div>Valid files are firmware.bin or littlefs.bin</div>"
    "</div>"
    "</body>"
    "<script>"
    "var prg = document.getElementById('prg');"
    "var form = document.getElementById('upload-form');"
    "var releaseInfo = document.getElementById('release-info');"
    "var installBtn = document.getElementById('install-btn');"
    "var downloadProgress = document.getElementById('download-progress');"
    "var dlPrg = document.getElementById('dl-prg');"
    "var githubSection = document.getElementById('github-release-section');"
    "var currentReleaseData = null;"
    
    "function compareVersions(current, latest) {"
    "var parseCurrent = current.match(/(\\d+)\\.(\\d+)\\.(\\d+)/);"
    "var parseLatest = latest.match(/(\\d+)\\.(\\d+)\\.(\\d+)/);"
    "if (!parseCurrent || !parseLatest) return false;"
    "var cYear = parseInt(parseCurrent[1]), cMonth = parseInt(parseCurrent[2]), cDay = parseInt(parseCurrent[3]);"
    "var lYear = parseInt(parseLatest[1]), lMonth = parseInt(parseLatest[2]), lDay = parseInt(parseLatest[3]);"
    "if (lYear !== cYear) return lYear > cYear;"
    "if (lMonth !== cMonth) return lMonth > cMonth;"
    "return lDay > cDay;"
    "}"
    
    "function checkForUpdates() {"
    "fetch('/configJSON')"
    ".then(r => r.json())"
    ".then(config => {"
    "var currentVersion = config.firmwareVersion || 'unknown';"
    "return fetch('https://api.github.com/repos/doudar/SmartSpin2k/releases/latest')"
    ".then(r => r.json())"
    ".then(release => {"
    "var tagName = release.tag_name || '';"
    "var releaseName = release.name || '';"
    "var assetUrl = '';"
    "if (release.assets) {"
    "for (var i = 0; i < release.assets.length; i++) {"
    "var assetName = release.assets[i].name || '';"
    "if (assetName.endsWith('.bin.zip') || assetName.endsWith('.bin')) {"
    "assetUrl = release.assets[i].browser_download_url;"
    "break;"
    "}"
    "}"
    "}"
    "if (!assetUrl) {"
    "console.log('No firmware asset found in release');"
    "return;"
    "}"
    "var isNewer = compareVersions(currentVersion, tagName);"
    "currentReleaseData = {"
    "currentVersion: currentVersion,"
    "latestVersion: tagName,"
    "releaseName: releaseName,"
    "assetUrl: assetUrl,"
    "isZipped: assetUrl.endsWith('.zip')"
    "};"
    "githubSection.style.display = 'block';"
    "let msg = '<strong>Current:</strong> ' + currentVersion + '<br>';"
    "msg += '<strong>Latest:</strong> ' + tagName + '<br>';"
    "if (isNewer) {"
    "msg += '<strong style=\"color:#28a745;\">New version available!</strong><br>';"
    "msg += '<strong>Release:</strong> ' + releaseName;"
    "installBtn.style.display = 'block';"
    "} else {"
    "msg += '<strong style=\"color:#007bff;\">You are up to date!</strong>';"
    "}"
    "releaseInfo.innerHTML = msg;"
    "});"
    "})"
    ".catch(e => {"
    "console.error('Error checking for updates:', e);"
    "});"
    "}"
    
    "window.addEventListener('load', function() {"
    "checkForUpdates();"
    "});"
    
    "function extractBinFromZip(zipBlob, callback) {"
    "var reader = new FileReader();"
    "reader.onload = function(e) {"
    "var data = new Uint8Array(e.target.result);"
    "var pos = 0;"
    "while (pos < data.length - 30) {"
    "if (data[pos] === 0x50 && data[pos+1] === 0x4B && data[pos+2] === 0x03 && data[pos+3] === 0x04) {"
    "var nameLen = data[pos+26] | (data[pos+27] << 8);"
    "var extraLen = data[pos+28] | (data[pos+29] << 8);"
    "var compSize = data[pos+18] | (data[pos+19] << 8) | (data[pos+20] << 16) | (data[pos+21] << 24);"
    "var fileName = String.fromCharCode.apply(null, data.slice(pos+30, pos+30+nameLen));"
    "if (fileName.endsWith('.bin')) {"
    "var fileStart = pos + 30 + nameLen + extraLen;"
    "var binData = data.slice(fileStart, fileStart + compSize);"
    "callback(new Blob([binData], {type: 'application/octet-stream'}));"
    "return;"
    "}"
    "pos += 30 + nameLen + extraLen + compSize;"
    "} else {"
    "pos++;"
    "}"
    "}"
    "callback(null);"
    "};"
    "reader.readAsArrayBuffer(zipBlob);"
    "}"
    
    "function uploadFirmware(blob) {"
    "releaseInfo.innerHTML = 'Uploading to device...';"
    "dlPrg.style.backgroundColor = '#28a745';"
    "dlPrg.innerHTML = 'Uploading...';"
    "var formData = new FormData();"
    "formData.append('update', blob, 'firmware.bin');"
    "var uploadXhr = new XMLHttpRequest();"
    "uploadXhr.open('POST', '/update');"
    "uploadXhr.upload.onprogress = function(e) {"
    "if (e.lengthComputable) {"
    "var percentComplete = Math.round((e.loaded / e.total) * 100);"
    "prg.style.width = percentComplete + '%';"
    "prg.innerHTML = percentComplete + '%';"
    "}"
    "};"
    "uploadXhr.onload = function() {"
    "if (uploadXhr.status === 200) {"
    "prg.style.backgroundColor = '#04AA6D';"
    "prg.innerHTML = 'Success! Device is rebooting...';"
    "releaseInfo.innerHTML = '<strong style=\"color:#28a745;\">Update successful! Device is rebooting...</strong>';"
    "downloadProgress.style.display = 'none';"
    "} else {"
    "prg.innerHTML = 'Upload failed';"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">Upload failed. Please try again.</strong>';"
    "installBtn.style.display = 'block';"
    "}"
    "};"
    "uploadXhr.onerror = function() {"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">Upload error. Please try again.</strong>';"
    "installBtn.style.display = 'block';"
    "};"
    "uploadXhr.send(formData);"
    "}"
    
    "function downloadAndInstall() {"
    "if (!currentReleaseData || !currentReleaseData.assetUrl) {"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">No release data available</strong>';"
    "return;"
    "}"
    "if (confirm('This will download and install firmware version ' + currentReleaseData.latestVersion + '. The device will reboot. Continue?')) {"
    "installBtn.style.display = 'none';"
    "downloadProgress.style.display = 'block';"
    "releaseInfo.innerHTML = 'Downloading firmware from GitHub...';"
    "dlPrg.style.width = '0%';"
    "dlPrg.innerHTML = '0%';"
    "var xhr = new XMLHttpRequest();"
    "xhr.open('GET', currentReleaseData.assetUrl, true);"
    "xhr.responseType = 'blob';"
    "xhr.onprogress = function(e) {"
    "if (e.lengthComputable) {"
    "var percentComplete = Math.round((e.loaded / e.total) * 100);"
    "dlPrg.style.width = percentComplete + '%';"
    "dlPrg.innerHTML = percentComplete + '%';"
    "}"
    "};"
    "xhr.onload = function() {"
    "if (xhr.status === 200) {"
    "var blob = xhr.response;"
    "if (currentReleaseData.isZipped) {"
    "releaseInfo.innerHTML = 'Extracting firmware from zip...';"
    "dlPrg.innerHTML = 'Extracting...';"
    "extractBinFromZip(blob, function(binBlob) {"
    "if (binBlob) {"
    "uploadFirmware(binBlob);"
    "} else {"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">Failed to extract firmware from zip.</strong>';"
    "installBtn.style.display = 'block';"
    "downloadProgress.style.display = 'none';"
    "}"
    "});"
    "} else {"
    "uploadFirmware(blob);"
    "}"
    "} else {"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">Download failed. Please try again.</strong>';"
    "installBtn.style.display = 'block';"
    "downloadProgress.style.display = 'none';"
    "}"
    "};"
    "xhr.onerror = function() {"
    "releaseInfo.innerHTML = '<strong style=\"color:#dc3545;\">Download error. Please check your internet connection.</strong>';"
    "installBtn.style.display = 'block';"
    "downloadProgress.style.display = 'none';"
    "};"
    "xhr.send();"
    "}"
    "}"
    
    "form.addEventListener('submit', e=>{"
    "e.preventDefault();"
    "var data = new FormData(form);"
    "var req = new XMLHttpRequest();"
    "req.open('POST', '/update');"
    "req.upload.addEventListener('progress', p=>{"
    "let w = Math.round((p.loaded / p.total)*100) + '%';"
    "if(p.lengthComputable){"
    "prg.innerHTML = w;"
    "prg.style.width = w;"
    "}"
    "if(w == '100%'){"
    "prg.style.backgroundColor = '#04AA6D';"
    "prg.innerHTML = 'Success! You can leave this page.';"
    "}"
    "});"
    "req.send(data);"
    "});"
    "</script>";
