/*
 * Copyright (C) 2020  Anthony Doud & Joel Baranick
 * All rights reserved
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#pragma once

#include <Arduino.h>
#include "settings.h"

String OTAStyle =
    "<style>"
    "html{font-family:system-ui,-apple-system,sans-serif;background:#03245c;color:#fff}"
    "body{box-sizing:border-box;margin:0;min-height:100vh;padding:20px;background:#1167b1;font-size:14px}"
    ".card{box-sizing:border-box;max-width:420px;margin:5vh auto;padding:24px;background:rgba(3,37,76,.75);border:1px solid rgba(255,255,255,.12);border-radius:12px;box-shadow:0 8px 16px rgba(0,0,0,.2)}"
    "h1,h2{margin:0 0 16px;text-align:center}h1{font-size:28px;text-shadow:0 4px 8px #0008}.sub{margin:-10px 0 20px;text-align:center;color:#2a9df4;font-size:18px;font-weight:600}"
    "form{max-width:360px;margin:16px auto;text-align:center}"
    "input{box-sizing:border-box;width:100%;margin:6px 0;padding:12px;border:1px solid #ffffff33;border-radius:6px;background:#ffffff1c;color:#fff;font-size:15px}"
    "input::placeholder,.hint{color:#ffffffb3}.btn{background:#2a9df4;color:#fff;cursor:pointer;border:0;font-weight:600}.btn:hover{background:#1b8fe3}.secondary{background:#ffffff1c;border:1px solid #ffffff33}.secondary:hover{background:#ffffff2b}"
    ".return-link{box-sizing:border-box;display:none;width:100%;max-width:360px;margin:16px auto 0;padding:12px;border-radius:6px;text-align:center;text-decoration:none}"
    ".track{height:24px;margin-top:14px;background:#0003;border-radius:8px;overflow:hidden}.fill{display:flex;align-items:center;justify-content:center;width:0;height:100%;background:#2a9df4;color:#fff;transition:width .15s}"
    ".hint{margin-top:12px;text-align:center;font-size:13px}#status{min-height:20px;margin-top:10px;text-align:center;font-weight:600}a{color:#fff}"
    "</style>";

/* Login page */
String OTALoginIndex =
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<main class='card'>"
    "<h1>SmartSpin2k</h1><div class='sub'>Firmware Update</div>"
    "<form name='loginForm' onsubmit='return check(this)'>"
    "<input name='userid' placeholder='User ID' autocomplete='username'>"
    "<input type='password' name='pwd' placeholder='Password' autocomplete='current-password'>"
    "<input type='submit' class='btn' value='Login'>"
    "</form>"
    "</main>"
    "<script>"
    "function check(form) {"
    "if(form.userid.value=='admin' && form.pwd.value=='admin'){"
    "location.href='/OTAIndex';"
    "}else{"
    "alert('Error: Incorrect Username or Password');"
    "}"
    "return false;"
    "}"
    "</script>" +
    OTAStyle;

String noIndexHTML =
    "<!DOCTYPE html>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<main class='card'>"
    "<h1>SmartSpin2k</h1><div class='sub'>Setup Required</div>"
    "<p class='hint'>Web files are missing. Connect to Wi-Fi for automatic recovery or upload a filesystem image.</p>"
    "<form action='/send_settings'>"
    "<input type='text' id='ssid' name='ssid' placeholder='Wi-Fi network' autocomplete='off'>"
    "<input type='password' id='password' name='password' placeholder='Wi-Fi password' autocomplete='off'>"
    "<input type='submit' value='Connect' class='btn'>"
    "</form>"
    "<form action='/reboot.html'>"
    "<input type='submit' value='Reboot' class='btn secondary'>"
    "</form>"
    "<p class='hint'><a href='login'><strong>Upload firmware or filesystem</strong></a></p>"
    "</main>" +
    OTAStyle;

/* Server Index Page */
String OTAServerIndex =
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<main class='card'>"
    "<h1>SmartSpin2k</h1><div class='sub'>Firmware Update</div>"
    "<form method='POST' action='#' enctype='multipart/form-data' id='upload-form'>"
    "<input type='file' id='update-file' name='update' accept='.bin'>"
    "<input type='submit' value='Install Update' class='btn'>"
    "</form>"
    "<div class='track'><div id='prg' class='fill'></div></div>"
    "<div class='hint'>Valid files: " FW_BINFILE " or " FS_BINFILE "</div>"
    "<div id='status' role='status'></div>"
    "<a href='/index.html' id='main-page' class='btn return-link'>Return to Main Page</a>"
    "</main>"
    "<script>"
    "var prg = document.getElementById('prg');"
    "var form = document.getElementById('upload-form');"
    "var fileInput = document.getElementById('update-file');"
    "var statusMessage = document.getElementById('status');"
    "var mainPageLink = document.getElementById('main-page');"
    "var expectedFirmware = '" FW_BINFILE "';"
    "var expectedFilesystem = '" FS_BINFILE "';"
    "function showStatus(message, isError){"
    "statusMessage.textContent = message;"
    "statusMessage.style.color = isError ? '#ff8a80' : '#7ee787';"
    "}"
    "function waitForReboot(){"
    "var down=false;"
    "var poll=setInterval(()=>{"
    "fetch('/configJSON',{cache:'no-store'}).then(r=>{"
    "if(down&&r.ok){"
    "clearInterval(poll);"
    "prg.style.backgroundColor='#04AA6D';"
    "prg.innerHTML='Ready';"
    "showStatus('Reboot complete. The device is back online.',false);"
    "mainPageLink.style.display='block';"
    "}"
    "}).catch(()=>{down=true;showStatus('Device is rebooting...',false);});"
    "},500);"
    "}"
    "form.addEventListener('submit', e=>{"
    "e.preventDefault();"
    "var file = fileInput.files[0];"
    "if(!file){"
    "showStatus('Select a firmware or filesystem image first.', true);"
    "return;"
    "}"
    "if(file.name !== expectedFirmware && file.name !== expectedFilesystem){"
    "showStatus('File \"' + file.name + '\" does not match this device. Expected ' + expectedFirmware + ' or ' + expectedFilesystem + '.', true);"
    "return;"
    "}"
    "mainPageLink.style.display='none';"
    "showStatus('Uploading ' + file.name + '...', false);"
    "var data = new FormData(form);"
    "var req = new XMLHttpRequest();"
    "req.open('POST', '/update');"
    "req.upload.addEventListener('progress', p=>{"
    "let w = Math.round((p.loaded / p.total)*100) + '%';"
    "if(p.lengthComputable){"
    "prg.innerHTML = w;"
    "prg.style.width = w;"
    "}"
    "if(w == '100%'){"
    "prg.innerHTML = 'Processing...';"
    "}"
    "});"
    "req.addEventListener('load', ()=>{"
    "if(req.status >= 200 && req.status < 300){"
    "prg.style.backgroundColor = '#2a9df4';"
    "prg.innerHTML = 'Waiting for reboot';"
    "showStatus('Update accepted. Waiting for the device to restart...', false);"
    "waitForReboot();"
    "}else{"
    "prg.style.backgroundColor = '#b00020';"
    "prg.innerHTML = 'Failed';"
    "showStatus(req.responseText || 'The update was rejected by the device.', true);"
    "}"
    "});"
    "req.addEventListener('error', ()=>{"
    "prg.style.backgroundColor = '#b00020';"
    "prg.innerHTML = 'Failed';"
    "showStatus('Upload failed. Check the connection and try again.', true);"
    "});"
    "req.send(data);"
    "});"
    "</script>" +
    OTAStyle;
